### PR TITLE
Buglets...

### PR DESCRIPTION
**Pull request by HSorensen**
This pull request is a collection of fixes I have found during installing and using the git version of antlr4ide.
- Testing revealed a missing log4j class
- Corrected handling of package action so the correct target folder is being used
- Fixed problem on property page when listing selected antlr tool jar files
- Fixed problem related to project specific settings

### CODE REVIEW

**Comment by HSorensen** [comment]
I have sent the pull request, but unless the owner actually pulls the code or show interest in fixing the problems it doesn't really matter what we do:)

**Comment by jknack** [comment]
Hi @HSorensen 

 I can merge the pull request (sorry been busy) but I also need help with the distribution (bintray, or something else).

 Would you like to be a member of this project? You can path and do whatever is best the project.

  Apologies, but I can't actively maintain the project for now.

Thanks

**Comment by HSorensen** [comment]
Yes you can add me to the project. I'll try to see if I can figure out how
to help

Henrik

**Comment by KristofSzabados** [comment]
Would it be possible to re-run the tests?
As far as I can tell the merge failed because of some environment issue.

**Comment by jonkblack** [comment]
I believe that https://github.com/jknack/antlr4ide/pull/144 also failed due to the same environment issue.

**Comment by arifogel** [comment]
@jknack Can you add me as a collaborator as well? I could spend some time with @HSorensen trying to get things back in a working state. I'm also anxious to get #144 merged.

**Comment by jknack** [comment]
@arifogel done

**Comment by arifogel** [comment]
Hey @HSorensen I tried the suggested travis fix in my pull request and it worked. I just merged my stuff into master. Please merge master into your branch, and travis will rerun automatically. If all is good, then we can merge this and finally close this request.

**Pull request merged**
